In [1]:
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import text as query_text
from sqlalchemy.sql import func


app = Flask(__name__)
PASSWORD = "abc#123456" # https://yaochi.console.aliyun.com/overview
app.config['SQLALCHEMY_DATABASE_URI'] = f'mysql+mysqlconnector://karibu:{PASSWORD}@rm-cn-lbj3dxzvu001t24o.rwlb.rds.aliyuncs.com:3306/movie'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False 
app.config['SQLALCHEMY_ECHO'] = True
app.app_context().push()

db = SQLAlchemy(app)

### Create the database and input data from SQL file

In [2]:
sql_script = ("""
DROP TABLE IF EXISTS movie_info;

CREATE TABLE IF NOT EXISTS movie_info (
    movie_id INT AUTO_INCREMENT PRIMARY KEY,
    movie_name VARCHAR(20) NOT NULL,
    release_date DATETIME,
    country VARCHAR(20),
    movie_type VARCHAR(10),
    release_year INT CHECK (release_year >= 1000 AND release_year <= 2100)
);


insert into movie_info
values('1001','战狼2','2017/7/27','中国','战争','2017');

insert into movie_info
values('1002','哪吒之魔童降世','2019/7/26','中国','动画','2019');

insert into movie_info
values('1003','流浪地球','2019/2/5','中国','科幻','2019');

insert into movie_info
values('1004','复仇者联盟4','2019/4/24','美国','科幻','2019');

insert into movie_info
values('1005','红海行动','2018/2/16','中国','战争','2018');

insert into movie_info
values('1006','唐人街探案2','2018/2/16','中国','喜剧','2018');

insert into movie_info
values('1007','我不是药神','2018/7/5','中国','喜剧','2018');

insert into movie_info
values('1008','中国机长','2019/9/30','中国','剧情','2019');

insert into movie_info
values('1009','速度与激情8','2017/4/14','美国','动作','2017');

insert into movie_info
values('1010','西虹市首富','2018/7/27','中国','喜剧','2018');

insert into movie_info
values('1011','复仇者联盟3','2018/5/11','美国','科幻','2018');

insert into movie_info
values('1012','捉妖记2','2018/2/16','中国','喜剧','2018');

insert into movie_info
values('1013','八佰','2020/08/21','中国','战争','2020');

insert into movie_info
values('1014','姜子牙','2020/10/01','中国','动画','2020');

insert into movie_info
values('1015','我和我的家乡','2020/10/01','中国','剧情','2020');

insert into movie_info
values('1016','你好，李焕英','2021/02/12','中国','喜剧','2021');

insert into movie_info
values('1017','长津湖','2021/09/30','中国','战争','2021');

insert into movie_info
values('1018','速度与激情9','2021/05/21','中国','动作','2021');
""")
scripts = [sql.strip() for sql in sql_script.split(';')]
db.session.begin()
for sql in scripts:
    db.session.execute(query_text(sql))

db.session.commit()

2023-11-17 22:21:49,606 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-11-17 22:21:49,608 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-11-17 22:21:49,719 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-11-17 22:21:49,720 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-11-17 22:21:49,775 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-11-17 22:21:49,776 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-11-17 22:21:49,831 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-17 22:21:49,860 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS movie_info
2023-11-17 22:21:49,861 INFO sqlalchemy.engine.Engine [generated in 0.02847s] {}
2023-11-17 22:21:49,923 INFO sqlalchemy.engine.Engine CREATE TABLE IF NOT EXISTS movie_info (
    movie_id INT AUTO_INCREMENT PRIMARY KEY,
    movie_name VARCHAR(20) NOT NULL,
    release_date DATETIME,
    country VARCHAR(20),
    movie_type VARCHAR(10),
    release_year INT CHECK (release_year >= 1000 AND release_year <= 2100)
)
2023-11-17 22:21:49,925 INFO sqlalchemy.engine.Engine [generated in 0.02822s] {}
2023-11-17 22:21:50,003 INFO sqlalchemy.engine.Engine insert into movie_info
values('1001','战狼2','2017/7/27','中国','战争','2017')
2023-11-17 22:21:50,004 INFO sqlalchemy.engine.Engine [generated in 0.02725s] {}
2023-11-17 22:21:50,061 INFO sqlalchemy.engine.Engine insert into movie_info
values('1002','哪吒之魔童降世','2019/7/26','中国','动画','2019')
2023-11-17 22:21:50,062 INFO sqlalchemy.engine.Engine [generated in 0.02771s] {}
2023-11-17 22:21:50,121 INFO sqlalchemy.engine.Engine insert into movie_info
values('1003','流浪地球','2019/2/5','中国','科幻','2019')
2023-11-17 22:21:50,123 INFO sqlalchemy.engine.Engine [generated in 0.02931s] {}
2023-11-17 22:21:50,178 INFO sqlalchemy.engine.Engine insert into movie_info
values('1004','复仇者联盟4','2019/4/24','美国','科幻','2019')
2023-11-17 22:21:50,180 INFO sqlalchemy.engine.Engine [generated in 0.02788s] {}
2023-11-17 22:21:50,237 INFO sqlalchemy.engine.Engine insert into movie_info
values('1005','红海行动','2018/2/16','中国','战争','2018')
2023-11-17 22:21:50,239 INFO sqlalchemy.engine.Engine [generated in 0.02916s] {}
2023-11-17 22:21:50,297 INFO sqlalchemy.engine.Engine insert into movie_info
values('1006','唐人街探案2','2018/2/16','中国','喜剧','2018')
2023-11-17 22:21:50,299 INFO sqlalchemy.engine.Engine [generated in 0.03040s] {}
2023-11-17 22:21:50,363 INFO sqlalchemy.engine.Engine insert into movie_info
values('1007','我不是药神','2018/7/5','中国','喜剧','2018')
2023-11-17 22:21:50,365 INFO sqlalchemy.engine.Engine [generated in 0.02873s] {}
2023-11-17 22:21:50,428 INFO sqlalchemy.engine.Engine insert into movie_info
values('1008','中国机长','2019/9/30','中国','剧情','2019')
2023-11-17 22:21:50,430 INFO sqlalchemy.engine.Engine [generated in 0.03461s] {}
2023-11-17 22:21:50,488 INFO sqlalchemy.engine.Engine insert into movie_info
values('1009','速度与激情8','2017/4/14','美国','动作','2017')
2023-11-17 22:21:50,491 INFO sqlalchemy.engine.Engine [generated in 0.02985s] {}
2023-11-17 22:21:50,550 INFO sqlalchemy.engine.Engine insert into movie_info
values('1010','西虹市首富','2018/7/27','中国','喜剧','2018')
2023-11-17 22:21:50,553 INFO sqlalchemy.engine.Engine [generated in 0.03179s] {}
2023-11-17 22:21:50,616 INFO sqlalchemy.engine.Engine insert into movie_info
values('1011','复仇者联盟3','2018/5/11','美国','科幻','2018')
2023-11-17 22:21:50,618 INFO sqlalchemy.engine.Engine [generated in 0.03138s] {}
2023-11-17 22:21:50,677 INFO sqlalchemy.engine.Engine insert into movie_info
values('1012','捉妖记2','2018/2/16','中国','喜剧','2018')
2023-11-17 22:21:50,679 INFO sqlalchemy.engine.Engine [generated in 0.02886s] {}
2023-11-17 22:21:50,739 INFO sqlalchemy.engine.Engine insert into movie_info
values('1013','八佰','2020/08/21','中国','战争','2020')
2023-11-17 22:21:50,742 INFO sqlalchemy.engine.Engine [generated in 0.03113s] {}
2023-11-17 22:21:50,802 INFO sqlalchemy.engine.Engine insert into movie_info
values('1014','姜子牙','2020/10/01','中国','动画','2020')
2023-11-17 22:21:50,807 INFO sqlalchemy.engine.Engine [generated in 0.03248s] {}
2023-11-17 22:21:50,868 INFO sqlalchemy.engine.Engine insert into movie_info
values('1015','我和我的家乡','2020/10/01','中国','剧情','2020')
2023-11-17 22:21:50,870 INFO sqlalchemy.engine.Engine [generated in 0.02830s] {}
2023-11-17 22:21:50,935 INFO sqlalchemy.engine.Engine insert into movie_info
values('1016','你好，李焕英','2021/02/12','中国','喜剧','2021')
2023-11-17 22:21:50,941 INFO sqlalchemy.engine.Engine [generated in 0.04196s] {}
2023-11-17 22:21:50,997 INFO sqlalchemy.engine.Engine insert into movie_info
values('1017','长津湖','2021/09/30','中国','战争','2021')
2023-11-17 22:21:50,998 INFO sqlalchemy.engine.Engine [generated in 0.02746s] {}
2023-11-17 22:21:51,062 INFO sqlalchemy.engine.Engine insert into movie_info
values('1018','速度与激情9','2021/05/21','中国','动作','2021')
2023-11-17 22:21:51,063 INFO sqlalchemy.engine.Engine [generated in 0.03119s] {}
2023-11-17 22:21:51,124 INFO sqlalchemy.engine.Engine
2023-11-17 22:21:51,126 INFO sqlalchemy.engine.Engine [generated in 0.03402s] {}
2023-11-17 22:21:51,128 INFO sqlalchemy.engine.Engine COMMIT

In [3]:
sql_script = ("""
DROP TABLE IF EXISTS movie_box;

CREATE TABLE IF NOT EXISTS movie_box (
    movie_id INT AUTO_INCREMENT PRIMARY KEY,
    movie_box float
);

insert into movie_box
values('1001',56.84);

insert into movie_box
values('1002',50.15);

insert into movie_box
values('1003',46.86);

insert into movie_box
values('1004',42.5);

insert into movie_box
values('1005',36.5);

insert into movie_box
values('1006',33.97);

insert into movie_box
values('1007',31);

insert into movie_box
values('1008',29.12);

insert into movie_box
values('1009',26.7);

insert into movie_box
values('1010',25.47);

insert into movie_box
values('1011',23.9);

insert into movie_box
values('1012',22.37);

insert into movie_box
values('1013',30.10);

insert into movie_box
values('1014',16.02);

insert into movie_box
values('1015',28.29);

insert into movie_box
values('1016',54.13);

insert into movie_box
values('1017',53.48);

insert into movie_box
values('1018',13.92);
""")
scripts = [sql.strip() for sql in sql_script.split(';')]
db.session.begin()
for sql in scripts:
    db.session.execute(query_text(sql))

db.session.commit()

2023-11-17 22:21:51,207 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-17 22:21:51,239 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS movie_box
2023-11-17 22:21:51,242 INFO sqlalchemy.engine.Engine [generated in 0.03212s] {}
2023-11-17 22:21:51,301 INFO sqlalchemy.engine.Engine CREATE TABLE IF NOT EXISTS movie_box (
    movie_id INT AUTO_INCREMENT PRIMARY KEY,
    movie_box float
)
2023-11-17 22:21:51,304 INFO sqlalchemy.engine.Engine [generated in 0.02865s] {}
2023-11-17 22:21:51,367 INFO sqlalchemy.engine.Engine insert into movie_box
values('1001',56.84)
2023-11-17 22:21:51,368 INFO sqlalchemy.engine.Engine [generated in 0.02747s] {}
2023-11-17 22:21:51,424 INFO sqlalchemy.engine.Engine insert into movie_box
values('1002',50.15)
2023-11-17 22:21:51,426 INFO sqlalchemy.engine.Engine [generated in 0.02868s] {}
2023-11-17 22:21:51,480 INFO sqlalchemy.engine.Engine insert into movie_box
values('1003',46.86)
2023-11-17 22:21:51,482 INFO sqlalchemy.engine.Engine [generated in 0.02773s] {}
2023-11-17 22:21:51,539 INFO sqlalchemy.engine.Engine insert into movie_box
values('1004',42.5)
2023-11-17 22:21:51,541 INFO sqlalchemy.engine.Engine [generated in 0.03008s] {}
2023-11-17 22:21:51,599 INFO sqlalchemy.engine.Engine insert into movie_box
values('1005',36.5)
2023-11-17 22:21:51,601 INFO sqlalchemy.engine.Engine [generated in 0.02837s] {}
2023-11-17 22:21:51,656 INFO sqlalchemy.engine.Engine insert into movie_box
values('1006',33.97)
2023-11-17 22:21:51,658 INFO sqlalchemy.engine.Engine [generated in 0.02864s] {}
2023-11-17 22:21:51,717 INFO sqlalchemy.engine.Engine insert into movie_box
values('1007',31)
2023-11-17 22:21:51,719 INFO sqlalchemy.engine.Engine [generated in 0.02846s] {}
2023-11-17 22:21:51,775 INFO sqlalchemy.engine.Engine insert into movie_box
values('1008',29.12)
2023-11-17 22:21:51,777 INFO sqlalchemy.engine.Engine [generated in 0.02816s] {}
2023-11-17 22:21:51,831 INFO sqlalchemy.engine.Engine insert into movie_box
values('1009',26.7)
2023-11-17 22:21:51,833 INFO sqlalchemy.engine.Engine [generated in 0.02773s] {}
2023-11-17 22:21:51,887 INFO sqlalchemy.engine.Engine insert into movie_box
values('1010',25.47)
2023-11-17 22:21:51,890 INFO sqlalchemy.engine.Engine [generated in 0.02997s] {}
2023-11-17 22:21:51,951 INFO sqlalchemy.engine.Engine insert into movie_box
values('1011',23.9)
2023-11-17 22:21:51,953 INFO sqlalchemy.engine.Engine [generated in 0.02779s] {}
2023-11-17 22:21:52,009 INFO sqlalchemy.engine.Engine insert into movie_box
values('1012',22.37)
2023-11-17 22:21:52,010 INFO sqlalchemy.engine.Engine [generated in 0.02837s] {}
2023-11-17 22:21:52,066 INFO sqlalchemy.engine.Engine insert into movie_box
values('1013',30.10)
2023-11-17 22:21:52,068 INFO sqlalchemy.engine.Engine [generated in 0.02746s] {}
2023-11-17 22:21:52,124 INFO sqlalchemy.engine.Engine insert into movie_box
values('1014',16.02)
2023-11-17 22:21:52,125 INFO sqlalchemy.engine.Engine [generated in 0.02905s] {}
2023-11-17 22:21:52,180 INFO sqlalchemy.engine.Engine insert into movie_box
values('1015',28.29)
2023-11-17 22:21:52,181 INFO sqlalchemy.engine.Engine [generated in 0.02748s] {}
2023-11-17 22:21:52,239 INFO sqlalchemy.engine.Engine insert into movie_box
values('1016',54.13)
2023-11-17 22:21:52,241 INFO sqlalchemy.engine.Engine [generated in 0.03194s] {}
2023-11-17 22:21:52,302 INFO sqlalchemy.engine.Engine insert into movie_box
values('1017',53.48)
2023-11-17 22:21:52,303 INFO sqlalchemy.engine.Engine [generated in 0.02990s] {}
2023-11-17 22:21:52,363 INFO sqlalchemy.engine.Engine insert into movie_box
values('1018',13.92)
2023-11-17 22:21:52,365 INFO sqlalchemy.engine.Engine [generated in 0.03183s] {}
2023-11-17 22:21:52,423 INFO sqlalchemy.engine.Engine
2023-11-17 22:21:52,425 INFO sqlalchemy.engine.Engine [cached since 1.333s ago] {}
2023-11-17 22:21:52,427 INFO sqlalchemy.engine.Engine COMMIT

In [4]:
sql_script = ("""
DROP TABLE IF EXISTS actor_info;

CREATE TABLE IF NOT EXISTS actor_info (
 actor_id INT AUTO_INCREMENT PRIMARY KEY,
 actor_name varchar(20) Not Null,
 gender varchar(2) Not Null,
 country varchar(20)
);

insert into actor_info
values('2001','吴京','男','中国');

insert into actor_info
values('2002','饺子','男','中国');

insert into actor_info
values('2003','屈楚萧','男','中国');

insert into actor_info
values('2004','郭帆','男','中国');

insert into actor_info
values('2005','乔罗素','男','美国');

insert into actor_info
values('2006','小罗伯特·唐尼','男','美国');

insert into actor_info
values('2007','克里斯·埃文斯','男','美国');

insert into actor_info
values('2008','林超贤','男','中国');

insert into actor_info
values('2009','张译','男','中国');

insert into actor_info
values('2010','黄景瑜','男','中国');

insert into actor_info
values('2011','陈思诚','男','中国');

insert into actor_info
values('2012','王宝强','男','中国');

insert into actor_info
values('2013','刘昊然','男','中国');

insert into actor_info
values('2014','文牧野','男','中国');

insert into actor_info
values('2015','徐峥','男','中国');

insert into actor_info
values('2016','刘伟强','男','中国');

insert into actor_info
values('2017','张涵予','男','中国');

insert into actor_info
values('2018','F·加里·格雷','男','美国');

insert into actor_info
values('2019','范·迪塞尔','男','美国');

insert into actor_info
values('2020','杰森·斯坦森','男','美国');

insert into actor_info
values('2021','闫非','男','中国');

insert into actor_info
values('2022','沈腾','男','中国');

insert into actor_info
values('2023','安东尼·罗素','男','美国');

insert into actor_info
values('2024','克里斯·海姆斯沃斯','男','美国');

insert into actor_info
values('2025','许诚毅','男','中国');

insert into actor_info
values('2026','梁朝伟','男','中国');

insert into actor_info
values('2027','白百何','女','中国');

insert into actor_info
values('2028','井柏然','男','中国');

insert into actor_info
values('2029','管虎','男','中国');

insert into actor_info
values('2030','王千源','男','中国');

insert into actor_info
values('2031','姜武','男','中国');

insert into actor_info
values('2032','宁浩','男','中国');

insert into actor_info
values('2033','葛优','男','中国');

insert into actor_info
values('2034','范伟','男','中国');

insert into actor_info
values('2035','贾玲','女','中国');

insert into actor_info
values('2036','张小斐','女','中国');

insert into actor_info
values('2037','陈凯歌','男','中国');

insert into actor_info
values('2038','徐克','男','中国');

insert into actor_info
values('2039','易烊千玺','男','中国');

insert into actor_info
values('2040','林诣彬','男','美国');

insert into actor_info
values('2041','米歇尔·罗德里格兹','女','美国');
""")
scripts = [sql.strip() for sql in sql_script.split(';')]
db.session.begin()
for sql in scripts:
    db.session.execute(query_text(sql))

db.session.commit()

2023-11-17 22:21:52,516 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-17 22:21:52,548 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS actor_info
2023-11-17 22:21:52,550 INFO sqlalchemy.engine.Engine [generated in 0.02875s] {}
2023-11-17 22:21:52,613 INFO sqlalchemy.engine.Engine CREATE TABLE IF NOT EXISTS actor_info (
 actor_id INT AUTO_INCREMENT PRIMARY KEY,
 actor_name varchar(20) Not Null,
 gender varchar(2) Not Null,
 country varchar(20)
)
2023-11-17 22:21:52,614 INFO sqlalchemy.engine.Engine [generated in 0.02865s] {}
2023-11-17 22:21:52,678 INFO sqlalchemy.engine.Engine insert into actor_info
values('2001','吴京','男','中国')
2023-11-17 22:21:52,679 INFO sqlalchemy.engine.Engine [generated in 0.02921s] {}
2023-11-17 22:21:52,737 INFO sqlalchemy.engine.Engine insert into actor_info
values('2002','饺子','男','中国')
2023-11-17 22:21:52,742 INFO sqlalchemy.engine.Engine [generated in 0.03410s] {}
2023-11-17 22:21:52,799 INFO sqlalchemy.engine.Engine insert into actor_info
values('2003','屈楚萧','男','中国')
2023-11-17 22:21:52,800 INFO sqlalchemy.engine.Engine [generated in 0.02783s] {}
2023-11-17 22:21:52,855 INFO sqlalchemy.engine.Engine insert into actor_info
values('2004','郭帆','男','中国')
2023-11-17 22:21:52,856 INFO sqlalchemy.engine.Engine [generated in 0.02763s] {}
2023-11-17 22:21:52,912 INFO sqlalchemy.engine.Engine insert into actor_info
values('2005','乔罗素','男','美国')
2023-11-17 22:21:52,913 INFO sqlalchemy.engine.Engine [generated in 0.02839s] {}
2023-11-17 22:21:52,970 INFO sqlalchemy.engine.Engine insert into actor_info
values('2006','小罗伯特·唐尼','男','美国')
2023-11-17 22:21:52,971 INFO sqlalchemy.engine.Engine [generated in 0.02829s] {}
2023-11-17 22:21:53,028 INFO sqlalchemy.engine.Engine insert into actor_info
values('2007','克里斯·埃文斯','男','美国')
2023-11-17 22:21:53,029 INFO sqlalchemy.engine.Engine [generated in 0.02813s] {}
2023-11-17 22:21:53,086 INFO sqlalchemy.engine.Engine insert into actor_info
values('2008','林超贤','男','中国')
2023-11-17 22:21:53,088 INFO sqlalchemy.engine.Engine [generated in 0.02787s] {}
2023-11-17 22:21:53,142 INFO sqlalchemy.engine.Engine insert into actor_info
values('2009','张译','男','中国')
2023-11-17 22:21:53,143 INFO sqlalchemy.engine.Engine [generated in 0.02763s] {}
2023-11-17 22:21:53,201 INFO sqlalchemy.engine.Engine insert into actor_info
values('2010','黄景瑜','男','中国')
2023-11-17 22:21:53,202 INFO sqlalchemy.engine.Engine [generated in 0.02885s] {}
2023-11-17 22:21:53,259 INFO sqlalchemy.engine.Engine insert into actor_info
values('2011','陈思诚','男','中国')
2023-11-17 22:21:53,260 INFO sqlalchemy.engine.Engine [generated in 0.03032s] {}
2023-11-17 22:21:53,318 INFO sqlalchemy.engine.Engine insert into actor_info
values('2012','王宝强','男','中国')
2023-11-17 22:21:53,319 INFO sqlalchemy.engine.Engine [generated in 0.02759s] {}
2023-11-17 22:21:53,375 INFO sqlalchemy.engine.Engine insert into actor_info
values('2013','刘昊然','男','中国')
2023-11-17 22:21:53,376 INFO sqlalchemy.engine.Engine [generated in 0.02938s] {}
2023-11-17 22:21:53,437 INFO sqlalchemy.engine.Engine insert into actor_info
values('2014','文牧野','男','中国')
2023-11-17 22:21:53,439 INFO sqlalchemy.engine.Engine [generated in 0.03186s] {}
2023-11-17 22:21:53,492 INFO sqlalchemy.engine.Engine insert into actor_info
values('2015','徐峥','男','中国')
2023-11-17 22:21:53,494 INFO sqlalchemy.engine.Engine [generated in 0.02699s] {}
2023-11-17 22:21:53,552 INFO sqlalchemy.engine.Engine insert into actor_info
values('2016','刘伟强','男','中国')
2023-11-17 22:21:53,553 INFO sqlalchemy.engine.Engine [generated in 0.03146s] {}
2023-11-17 22:21:53,610 INFO sqlalchemy.engine.Engine insert into actor_info
values('2017','张涵予','男','中国')
2023-11-17 22:21:53,613 INFO sqlalchemy.engine.Engine [generated in 0.03052s] {}
2023-11-17 22:21:53,675 INFO sqlalchemy.engine.Engine insert into actor_info
values('2018','F·加里·格雷','男','美国')
2023-11-17 22:21:53,677 INFO sqlalchemy.engine.Engine [generated in 0.03108s] {}
2023-11-17 22:21:53,735 INFO sqlalchemy.engine.Engine insert into actor_info
values('2019','范·迪塞尔','男','美国')
2023-11-17 22:21:53,737 INFO sqlalchemy.engine.Engine [generated in 0.02867s] {}
2023-11-17 22:21:53,798 INFO sqlalchemy.engine.Engine insert into actor_info
values('2020','杰森·斯坦森','男','美国')
2023-11-17 22:21:53,799 INFO sqlalchemy.engine.Engine [generated in 0.02722s] {}
2023-11-17 22:21:53,856 INFO sqlalchemy.engine.Engine insert into actor_info
values('2021','闫非','男','中国')
2023-11-17 22:21:53,858 INFO sqlalchemy.engine.Engine [generated in 0.02863s] {}
2023-11-17 22:21:53,911 INFO sqlalchemy.engine.Engine insert into actor_info
values('2022','沈腾','男','中国')
2023-11-17 22:21:53,913 INFO sqlalchemy.engine.Engine [generated in 0.02727s] {}
2023-11-17 22:21:53,969 INFO sqlalchemy.engine.Engine insert into actor_info
values('2023','安东尼·罗素','男','美国')
2023-11-17 22:21:53,970 INFO sqlalchemy.engine.Engine [generated in 0.02939s] {}
2023-11-17 22:21:54,027 INFO sqlalchemy.engine.Engine insert into actor_info
values('2024','克里斯·海姆斯沃斯','男','美国')
2023-11-17 22:21:54,028 INFO sqlalchemy.engine.Engine [generated in 0.02914s] {}
2023-11-17 22:21:54,085 INFO sqlalchemy.engine.Engine insert into actor_info
values('2025','许诚毅','男','中国')
2023-11-17 22:21:54,086 INFO sqlalchemy.engine.Engine [generated in 0.03013s] {}
2023-11-17 22:21:54,147 INFO sqlalchemy.engine.Engine insert into actor_info
values('2026','梁朝伟','男','中国')
2023-11-17 22:21:54,149 INFO sqlalchemy.engine.Engine [generated in 0.03235s] {}
2023-11-17 22:21:54,210 INFO sqlalchemy.engine.Engine insert into actor_info
values('2027','白百何','女','中国')
2023-11-17 22:21:54,212 INFO sqlalchemy.engine.Engine [generated in 0.02767s] {}
2023-11-17 22:21:54,266 INFO sqlalchemy.engine.Engine insert into actor_info
values('2028','井柏然','男','中国')
2023-11-17 22:21:54,270 INFO sqlalchemy.engine.Engine [generated in 0.03086s] {}
2023-11-17 22:21:54,328 INFO sqlalchemy.engine.Engine insert into actor_info
values('2029','管虎','男','中国')
2023-11-17 22:21:54,330 INFO sqlalchemy.engine.Engine [generated in 0.02863s] {}
2023-11-17 22:21:54,393 INFO sqlalchemy.engine.Engine insert into actor_info
values('2030','王千源','男','中国')
2023-11-17 22:21:54,395 INFO sqlalchemy.engine.Engine [generated in 0.03415s] {}
2023-11-17 22:21:54,452 INFO sqlalchemy.engine.Engine insert into actor_info
values('2031','姜武','男','中国')
2023-11-17 22:21:54,453 INFO sqlalchemy.engine.Engine [generated in 0.02833s] {}
2023-11-17 22:21:54,514 INFO sqlalchemy.engine.Engine insert into actor_info
values('2032','宁浩','男','中国')
2023-11-17 22:21:54,517 INFO sqlalchemy.engine.Engine [generated in 0.03247s] {}
2023-11-17 22:21:54,574 INFO sqlalchemy.engine.Engine insert into actor_info
values('2033','葛优','男','中国')
2023-11-17 22:21:54,578 INFO sqlalchemy.engine.Engine [generated in 0.03230s] {}
2023-11-17 22:21:54,636 INFO sqlalchemy.engine.Engine insert into actor_info
values('2034','范伟','男','中国')
2023-11-17 22:21:54,638 INFO sqlalchemy.engine.Engine [generated in 0.03022s] {}
2023-11-17 22:21:54,696 INFO sqlalchemy.engine.Engine insert into actor_info
values('2035','贾玲','女','中国')
2023-11-17 22:21:54,697 INFO sqlalchemy.engine.Engine [generated in 0.02777s] {}
2023-11-17 22:21:54,758 INFO sqlalchemy.engine.Engine insert into actor_info
values('2036','张小斐','女','中国')
2023-11-17 22:21:54,760 INFO sqlalchemy.engine.Engine [generated in 0.03211s] {}
2023-11-17 22:21:54,817 INFO sqlalchemy.engine.Engine insert into actor_info
values('2037','陈凯歌','男','中国')
2023-11-17 22:21:54,819 INFO sqlalchemy.engine.Engine [generated in 0.02791s] {}
2023-11-17 22:21:54,879 INFO sqlalchemy.engine.Engine insert into actor_info
values('2038','徐克','男','中国')
2023-11-17 22:21:54,881 INFO sqlalchemy.engine.Engine [generated in 0.03116s] {}
2023-11-17 22:21:54,940 INFO sqlalchemy.engine.Engine insert into actor_info
values('2039','易烊千玺','男','中国')
2023-11-17 22:21:54,943 INFO sqlalchemy.engine.Engine [generated in 0.03295s] {}
2023-11-17 22:21:55,009 INFO sqlalchemy.engine.Engine insert into actor_info
values('2040','林诣彬','男','美国')
2023-11-17 22:21:55,011 INFO sqlalchemy.engine.Engine [generated in 0.03246s] {}
2023-11-17 22:21:55,069 INFO sqlalchemy.engine.Engine insert into actor_info
values('2041','米歇尔·罗德里格兹','女','美国')
2023-11-17 22:21:55,072 INFO sqlalchemy.engine.Engine [generated in 0.02944s] {}
2023-11-17 22:21:55,135 INFO sqlalchemy.engine.Engine
2023-11-17 22:21:55,137 INFO sqlalchemy.engine.Engine [cached since 4.045s ago] {}
2023-11-17 22:21:55,139 INFO sqlalchemy.engine.Engine COMMIT

In [5]:
sql_script = ("""
DROP TABLE IF EXISTS movie_actor_relation;
CREATE TABLE IF NOT EXISTS movie_actor_relation
( 
 id varchar(10) Not Null,
 movie_id INT Not Null,
 actor_id INT Not Null,
 relation_type varchar(20),
 primary key(id)
);


insert into movie_actor_relation
values('1','1001','2001','主演');

insert into movie_actor_relation
values('2','1001','2001','导演');

insert into movie_actor_relation
values('3','1002','2002','导演');

insert into movie_actor_relation
values('4','1003','2001','主演');

insert into movie_actor_relation
values('5','1003','2003','主演');

insert into movie_actor_relation
values('6','1003','2004','导演');

insert into movie_actor_relation
values('7','1004','2005','导演');

insert into movie_actor_relation
values('8','1004','2006','主演');

insert into movie_actor_relation
values('9','1004','2007','主演');

insert into movie_actor_relation
values('10','1005','2008','导演');

insert into movie_actor_relation
values('11','1005','2009','主演');

insert into movie_actor_relation
values('12','1005','2010','主演');

insert into movie_actor_relation
values('13','1006','2011','导演');

insert into movie_actor_relation
values('14','1006','2012','主演');

insert into movie_actor_relation
values('15','1006','2013','主演');

insert into movie_actor_relation
values('16','1007','2014','导演');

insert into movie_actor_relation
values('17','1007','2015','主演');

insert into movie_actor_relation
values('18','1008','2016','导演');

insert into movie_actor_relation
values('19','1008','2017','主演');

insert into movie_actor_relation
values('20','1009','2018','导演');

insert into movie_actor_relation
values('21','1009','2019','主演');

insert into movie_actor_relation
values('22','1009','2020','主演');

insert into movie_actor_relation
values('23','1010','2021','导演');

insert into movie_actor_relation
values('24','1010','2022','主演');

insert into movie_actor_relation
values('25','1011','2023','导演');

insert into movie_actor_relation
values('26','1011','2006','主演');

insert into movie_actor_relation
values('27','1011','2024','主演');

insert into movie_actor_relation
values('28','1012','2025','导演');

insert into movie_actor_relation
values('29','1012','2026','主演');

insert into movie_actor_relation
values('30','1012','2027','主演');

insert into movie_actor_relation
values('31','1012','2028','主演');

insert into movie_actor_relation
values('32','1013','2029','导演');

insert into movie_actor_relation
values('33','1013','2030','主演');

insert into movie_actor_relation
values('34','1013','2009','主演');

insert into movie_actor_relation
values('35','1013','2031','主演');

insert into movie_actor_relation
values('36','1015','2032','导演');

insert into movie_actor_relation
values('37','1015','2015','导演');

insert into movie_actor_relation
values('38','1015','2011','导演');

insert into movie_actor_relation
values('39','1015','2015','主演');

insert into movie_actor_relation
values('40','1015','2033','主演');

insert into movie_actor_relation
values('41','1015','2034','主演');

insert into movie_actor_relation
values('42','1016','2035','导演');

insert into movie_actor_relation
values('43','1016','2035','主演');

insert into movie_actor_relation
values('44','1016','2036','主演');

insert into movie_actor_relation
values('45','1016','2022','主演');

insert into movie_actor_relation
values('46','1017','2037','导演');

insert into movie_actor_relation
values('47','1017','2038','导演');

insert into movie_actor_relation
values('48','1017','2008','导演');

insert into movie_actor_relation
values('49','1017','2001','主演');

insert into movie_actor_relation
values('50','1017','2039','主演');

insert into movie_actor_relation
values('51','1018','2040','导演');

insert into movie_actor_relation
values('52','1018','2019','主演');

insert into movie_actor_relation
values('53','1018','2041','主演');

""")
scripts = [sql.strip() for sql in sql_script.split(';')]
db.session.begin()
for sql in scripts:
    db.session.execute(query_text(sql))

db.session.commit()

2023-11-17 22:21:55,223 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-17 22:21:55,254 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS movie_actor_relation
2023-11-17 22:21:55,256 INFO sqlalchemy.engine.Engine [generated in 0.02977s] {}
2023-11-17 22:21:55,319 INFO sqlalchemy.engine.Engine CREATE TABLE IF NOT EXISTS movie_actor_relation
(
 id varchar(10) Not Null,
 movie_id INT Not Null,
 actor_id INT Not Null,
 relation_type varchar(20),
 primary key(id)
)
2023-11-17 22:21:55,321 INFO sqlalchemy.engine.Engine [generated in 0.02749s] {}
2023-11-17 22:21:55,389 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('1','1001','2001','主演')
2023-11-17 22:21:55,390 INFO sqlalchemy.engine.Engine [generated in 0.02822s] {}
2023-11-17 22:21:55,449 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('2','1001','2001','导演')
2023-11-17 22:21:55,450 INFO sqlalchemy.engine.Engine [generated in 0.02920s] {}
2023-11-17 22:21:55,507 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('3','1002','2002','导演')
2023-11-17 22:21:55,511 INFO sqlalchemy.engine.Engine [generated in 0.03208s] {}
2023-11-17 22:21:55,574 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('4','1003','2001','主演')
2023-11-17 22:21:55,575 INFO sqlalchemy.engine.Engine [generated in 0.03013s] {}
2023-11-17 22:21:55,631 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('5','1003','2003','主演')
2023-11-17 22:21:55,633 INFO sqlalchemy.engine.Engine [generated in 0.02826s] {}
2023-11-17 22:21:55,691 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('6','1003','2004','导演')
2023-11-17 22:21:55,694 INFO sqlalchemy.engine.Engine [generated in 0.02887s] {}
2023-11-17 22:21:55,751 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('7','1004','2005','导演')
2023-11-17 22:21:55,752 INFO sqlalchemy.engine.Engine [generated in 0.02826s] {}
2023-11-17 22:21:55,812 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('8','1004','2006','主演')
2023-11-17 22:21:55,813 INFO sqlalchemy.engine.Engine [generated in 0.02943s] {}
2023-11-17 22:21:55,867 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('9','1004','2007','主演')
2023-11-17 22:21:55,868 INFO sqlalchemy.engine.Engine [generated in 0.02738s] {}
2023-11-17 22:21:55,924 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('10','1005','2008','导演')
2023-11-17 22:21:55,926 INFO sqlalchemy.engine.Engine [generated in 0.03014s] {}
2023-11-17 22:21:55,984 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('11','1005','2009','主演')
2023-11-17 22:21:55,986 INFO sqlalchemy.engine.Engine [generated in 0.02883s] {}
2023-11-17 22:21:56,044 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('12','1005','2010','主演')
2023-11-17 22:21:56,045 INFO sqlalchemy.engine.Engine [generated in 0.03011s] {}
2023-11-17 22:21:56,103 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('13','1006','2011','导演')
2023-11-17 22:21:56,105 INFO sqlalchemy.engine.Engine [generated in 0.02927s] {}
2023-11-17 22:21:56,161 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('14','1006','2012','主演')
2023-11-17 22:21:56,162 INFO sqlalchemy.engine.Engine [generated in 0.02869s] {}
2023-11-17 22:21:56,223 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('15','1006','2013','主演')
2023-11-17 22:21:56,225 INFO sqlalchemy.engine.Engine [generated in 0.02921s] {}
2023-11-17 22:21:56,283 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('16','1007','2014','导演')
2023-11-17 22:21:56,284 INFO sqlalchemy.engine.Engine [generated in 0.03114s] {}
2023-11-17 22:21:56,347 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('17','1007','2015','主演')
2023-11-17 22:21:56,348 INFO sqlalchemy.engine.Engine [generated in 0.03080s] {}
2023-11-17 22:21:56,406 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('18','1008','2016','导演')
2023-11-17 22:21:56,407 INFO sqlalchemy.engine.Engine [generated in 0.03103s] {}
2023-11-17 22:21:56,467 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('19','1008','2017','主演')
2023-11-17 22:21:56,468 INFO sqlalchemy.engine.Engine [generated in 0.02852s] {}
2023-11-17 22:21:56,525 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('20','1009','2018','导演')
2023-11-17 22:21:56,527 INFO sqlalchemy.engine.Engine [generated in 0.03155s] {}
2023-11-17 22:21:56,594 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('21','1009','2019','主演')
2023-11-17 22:21:56,595 INFO sqlalchemy.engine.Engine [generated in 0.02931s] {}
2023-11-17 22:21:56,653 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('22','1009','2020','主演')
2023-11-17 22:21:56,658 INFO sqlalchemy.engine.Engine [generated in 0.03273s] {}
2023-11-17 22:21:56,716 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('23','1010','2021','导演')
2023-11-17 22:21:56,718 INFO sqlalchemy.engine.Engine [generated in 0.02795s] {}
2023-11-17 22:21:56,774 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('24','1010','2022','主演')
2023-11-17 22:21:56,776 INFO sqlalchemy.engine.Engine [generated in 0.02809s] {}
2023-11-17 22:21:56,834 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('25','1011','2023','导演')
2023-11-17 22:21:56,836 INFO sqlalchemy.engine.Engine [generated in 0.03014s] {}
2023-11-17 22:21:56,895 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('26','1011','2006','主演')
2023-11-17 22:21:56,899 INFO sqlalchemy.engine.Engine [generated in 0.03140s] {}
2023-11-17 22:21:56,965 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('27','1011','2024','主演')
2023-11-17 22:21:56,967 INFO sqlalchemy.engine.Engine [generated in 0.03212s] {}
2023-11-17 22:21:57,024 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('28','1012','2025','导演')
2023-11-17 22:21:57,026 INFO sqlalchemy.engine.Engine [generated in 0.02987s] {}
2023-11-17 22:21:57,083 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('29','1012','2026','主演')
2023-11-17 22:21:57,085 INFO sqlalchemy.engine.Engine [generated in 0.02739s] {}
2023-11-17 22:21:57,160 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('30','1012','2027','主演')
2023-11-17 22:21:57,162 INFO sqlalchemy.engine.Engine [generated in 0.03503s] {}
2023-11-17 22:21:57,221 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('31','1012','2028','主演')
2023-11-17 22:21:57,224 INFO sqlalchemy.engine.Engine [generated in 0.03288s] {}
2023-11-17 22:21:57,283 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('32','1013','2029','导演')
2023-11-17 22:21:57,285 INFO sqlalchemy.engine.Engine [generated in 0.02936s] {}
2023-11-17 22:21:57,348 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('33','1013','2030','主演')
2023-11-17 22:21:57,349 INFO sqlalchemy.engine.Engine [generated in 0.03089s] {}
2023-11-17 22:21:57,414 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('34','1013','2009','主演')
2023-11-17 22:21:57,416 INFO sqlalchemy.engine.Engine [generated in 0.03308s] {}
2023-11-17 22:21:57,475 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('35','1013','2031','主演')
2023-11-17 22:21:57,476 INFO sqlalchemy.engine.Engine [generated in 0.02922s] {}
2023-11-17 22:21:57,535 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('36','1015','2032','导演')
2023-11-17 22:21:57,537 INFO sqlalchemy.engine.Engine [generated in 0.02714s] {}
2023-11-17 22:21:57,593 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('37','1015','2015','导演')
2023-11-17 22:21:57,595 INFO sqlalchemy.engine.Engine [generated in 0.02868s] {}
2023-11-17 22:21:57,659 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('38','1015','2011','导演')
2023-11-17 22:21:57,661 INFO sqlalchemy.engine.Engine [generated in 0.03229s] {}
2023-11-17 22:21:57,721 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('39','1015','2015','主演')
2023-11-17 22:21:57,723 INFO sqlalchemy.engine.Engine [generated in 0.02980s] {}
2023-11-17 22:21:57,792 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('40','1015','2033','主演')
2023-11-17 22:21:57,795 INFO sqlalchemy.engine.Engine [generated in 0.03924s] {}
2023-11-17 22:21:57,859 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('41','1015','2034','主演')
2023-11-17 22:21:57,861 INFO sqlalchemy.engine.Engine [generated in 0.03239s] {}
2023-11-17 22:21:57,932 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('42','1016','2035','导演')
2023-11-17 22:21:57,934 INFO sqlalchemy.engine.Engine [generated in 0.03848s] {}
2023-11-17 22:21:58,000 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('43','1016','2035','主演')
2023-11-17 22:21:58,001 INFO sqlalchemy.engine.Engine [generated in 0.02847s] {}
2023-11-17 22:21:58,059 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('44','1016','2036','主演')
2023-11-17 22:21:58,061 INFO sqlalchemy.engine.Engine [generated in 0.02819s] {}
2023-11-17 22:21:58,130 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('45','1016','2022','主演')
2023-11-17 22:21:58,132 INFO sqlalchemy.engine.Engine [generated in 0.03289s] {}
2023-11-17 22:21:58,191 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('46','1017','2037','导演')
2023-11-17 22:21:58,192 INFO sqlalchemy.engine.Engine [generated in 0.02989s] {}
2023-11-17 22:21:58,249 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('47','1017','2038','导演')
2023-11-17 22:21:58,251 INFO sqlalchemy.engine.Engine [generated in 0.02990s] {}
2023-11-17 22:21:58,312 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('48','1017','2008','导演')
2023-11-17 22:21:58,316 INFO sqlalchemy.engine.Engine [generated in 0.03264s] {}
2023-11-17 22:21:58,379 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('49','1017','2001','主演')
2023-11-17 22:21:58,381 INFO sqlalchemy.engine.Engine [generated in 0.03578s] {}
2023-11-17 22:21:58,445 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('50','1017','2039','主演')
2023-11-17 22:21:58,447 INFO sqlalchemy.engine.Engine [generated in 0.03417s] {}
2023-11-17 22:21:58,507 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('51','1018','2040','导演')
2023-11-17 22:21:58,508 INFO sqlalchemy.engine.Engine [generated in 0.02896s] {}
2023-11-17 22:21:58,574 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('52','1018','2019','主演')
2023-11-17 22:21:58,576 INFO sqlalchemy.engine.Engine [generated in 0.02792s] {}
2023-11-17 22:21:58,636 INFO sqlalchemy.engine.Engine insert into movie_actor_relation
values('53','1018','2041','主演')
2023-11-17 22:21:58,638 INFO sqlalchemy.engine.Engine [generated in 0.03157s] {}
2023-11-17 22:21:58,696 INFO sqlalchemy.engine.Engine
2023-11-17 22:21:58,700 INFO sqlalchemy.engine.Engine [cached since 7.608s ago] {}
2023-11-17 22:21:58,702 INFO sqlalchemy.engine.Engine COMMIT

### Create Relationship table for Actors

In [6]:
sql_script = """
DROP TABLE IF EXISTS movie_actor_association;

CREATE TABLE movie_actor_association AS
SELECT movie_id, actor_id
FROM movie_actor_relation
WHERE relation_type="主演";

"""
scripts = [sql.strip() for sql in sql_script.split(';')]
db.session.begin()
for sql in scripts:
    db.session.execute(query_text(sql))

db.session.commit()

2023-11-17 22:21:58,790 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-17 22:21:58,821 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS movie_actor_association
2023-11-17 22:21:58,823 INFO sqlalchemy.engine.Engine [generated in 0.02949s] {}
2023-11-17 22:21:58,886 INFO sqlalchemy.engine.Engine CREATE TABLE movie_actor_association AS
SELECT movie_id, actor_id
FROM movie_actor_relation
WHERE relation_type="主演"
2023-11-17 22:21:58,887 INFO sqlalchemy.engine.Engine [generated in 0.02796s] {}
2023-11-17 22:21:58,953 INFO sqlalchemy.engine.Engine
2023-11-17 22:21:58,955 INFO sqlalchemy.engine.Engine [cached since 7.864s ago] {}
2023-11-17 22:21:58,957 INFO sqlalchemy.engine.Engine COMMIT

In [7]:
sql_script = """
DROP TABLE IF EXISTS movie_director_association;

CREATE TABLE movie_director_association AS
SELECT movie_id, actor_id
FROM movie_actor_relation
WHERE relation_type="导演";
"""
scripts = [sql.strip() for sql in sql_script.split(';')]
db.session.begin()
for sql in scripts:
    db.session.execute(query_text(sql))

db.session.commit()

2023-11-17 22:21:59,029 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-17 22:21:59,063 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS movie_director_association
2023-11-17 22:21:59,068 INFO sqlalchemy.engine.Engine [generated in 0.03502s] {}
2023-11-17 22:21:59,129 INFO sqlalchemy.engine.Engine CREATE TABLE movie_director_association AS
SELECT movie_id, actor_id
FROM movie_actor_relation
WHERE relation_type="导演"
2023-11-17 22:21:59,130 INFO sqlalchemy.engine.Engine [generated in 0.02904s] {}
2023-11-17 22:21:59,193 INFO sqlalchemy.engine.Engine
2023-11-17 22:21:59,195 INFO sqlalchemy.engine.Engine [cached since 8.103s ago] {}
2023-11-17 22:21:59,197 INFO sqlalchemy.engine.Engine COMMIT

In [8]:

query = query_text("SELECT * FROM movie_info;")
db.session.execute(query).fetchall()

2023-11-17 22:21:59,265 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-17 22:21:59,299 INFO sqlalchemy.engine.Engine SELECT * FROM movie_info;
2023-11-17 22:21:59,304 INFO sqlalchemy.engine.Engine [generated in 0.03460s] {}

[(1001, '战狼2', datetime.datetime(2017, 7, 27, 0, 0), '中国', '战争', 2017),
 (1002, '哪吒之魔童降世', datetime.datetime(2019, 7, 26, 0, 0), '中国', '动画', 2019),
 (1003, '流浪地球', datetime.datetime(2019, 2, 5, 0, 0), '中国', '科幻', 2019),
 (1004, '复仇者联盟4', datetime.datetime(2019, 4, 24, 0, 0), '美国', '科幻', 2019),
 (1005, '红海行动', datetime.datetime(2018, 2, 16, 0, 0), '中国', '战争', 2018),
 (1006, '唐人街探案2', datetime.datetime(2018, 2, 16, 0, 0), '中国', '喜剧', 2018),
 (1007, '我不是药神', datetime.datetime(2018, 7, 5, 0, 0), '中国', '喜剧', 2018),
 (1008, '中国机长', datetime.datetime(2019, 9, 30, 0, 0), '中国', '剧情', 2019),
 (1009, '速度与激情8', datetime.datetime(2017, 4, 14, 0, 0), '美国', '动作', 2017),
 (1010, '西虹市首富', datetime.datetime(2018, 7, 27, 0, 0), '中国', '喜剧', 2018),
 (1011, '复仇者联盟3', datetime.datetime(2018, 5, 11, 0, 0), '美国', '科幻', 2018),
 (1012, '捉妖记2', datetime.datetime(2018, 2, 16, 0, 0), '中国', '喜剧', 2018),
 (1013, '八佰', datetime.datetime(2020, 8, 21, 0, 0), '中国', '战争', 2020),
 (1014, '姜子牙', datetime.datetime(2020, 10, 1, 0, 0), '中国', '动画', 2020),
 (1015, '我和我的家乡', datetime.datetime(2020, 10, 1, 0, 0), '中国', '剧情', 2020),
 (1016, '你好，李焕英', datetime.datetime(2021, 2, 12, 0, 0), '中国', '喜剧', 2021),
 (1017, '长津湖', datetime.datetime(2021, 9, 30, 0, 0), '中国', '战争', 2021),
 (1018, '速度与激情9', datetime.datetime(2021, 5, 21, 0, 0), '中国', '动作', 2021)]

In [9]:
query = query_text("SELECT * FROM movie_actor_association;")
db.session.execute(query).fetchall()

2023-11-17 22:21:59,387 INFO sqlalchemy.engine.Engine SELECT * FROM movie_actor_association;
2023-11-17 22:21:59,389 INFO sqlalchemy.engine.Engine [generated in 0.03167s] {}

[(1001, 2001),
 (1005, 2009),
 (1005, 2010),
 (1006, 2012),
 (1006, 2013),
 (1007, 2015),
 (1008, 2017),
 (1009, 2019),
 (1009, 2020),
 (1010, 2022),
 (1011, 2006),
 (1011, 2024),
 (1012, 2026),
 (1012, 2027),
 (1012, 2028),
 (1013, 2030),
 (1013, 2009),
 (1013, 2031),
 (1015, 2015),
 (1003, 2001),
 (1015, 2033),
 (1015, 2034),
 (1016, 2035),
 (1016, 2036),
 (1016, 2022),
 (1017, 2001),
 (1003, 2003),
 (1017, 2039),
 (1018, 2019),
 (1018, 2041),
 (1004, 2006),
 (1004, 2007)]